version: '3'
services:
  tresorRedis:
    image: 'redis'
    ports:
      - "6379"
    container_name: "tresorRedis"
  tresorDb:
    image: 'postgres'
    restart: 'always'
    volumes:
      - './dataDb/:/var/lib/postgresql/data/'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tresorDb
      - POSTGRES_USER=tresor
      - POSTGRES_PASSWORD=tresor123
    container_name: "tresorDb"      
  tresorWeb:
    image: 'node'
    volumes:
      - '.:/home/node/app'
    ports:
      - "3000:3000"
    working_dir: "/home/node/app/"
    depends_on:
      - tresorDb 
      - tresorRedis
    stdin_open: true
    tty: true
    container_name: "tresorWeb"
    
  

  