version: '3'
services:
  tresorDb:
    image: 'postgres'
    restart: 'always'
    volumes:
      - './dataDb:/var/lib/postgresql/'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tresor
      - POSTGRES_USER=tresorDb
      - POSTGRES_PASSWORD=tresor123
  tresorWeb:
    image: 'node'
    volumes:
      - '.:/home/node/app'
    ports:
      - "3000:3000"
    working_dir: "/home/node/app/"
    depends_on:
      - tresorDb 
    stdin_open: true
    tty: true
  

  